### ISSUE TITLE
Uncaught ReferenceError: firebase is not defined   

### ISSUE THREAD

**Issue by PetjaPaivarinta** [Varshithvhegde/anyshare#1]
i've copied the javascript code and proof read it through but it is saying firebase isn't defined, which in turn breaks uploading and makes it an infinite loop, did you go through this/do you have any idea why this issue is persisting, thanks

**Comment by Varshithvhegde** [comment]
message me via linkdn my linkdn username is varshithvhegde

**Comment by Varshithvhegde** [comment]
Its probably because CDN link is present in HTML file.
